name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  hotcoco:
    runs-on: ubuntu-latest

    steps:
      - name: Invoking hotcoco
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: 'http://bb90-104-245-156-31.ngrok.io/deploy'
          webhook_secret: 'mysecret'
